# k8s/billing-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: billing-service
  template:
    metadata:
      labels:
        app: billing-service
    spec:
      containers:
        - name: billing-service
          image: nextflop-billing-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              value: "your-super-secret-jwt-key-change-in-production"
            - name: MONGODB_URI
              value: "mongodb://admin:password123@mongodb-billing:27017/nextflop_billing?authSource=admin"
            - name: RABBITMQ_URL
              value: "amqp://admin:password123@rabbitmq:5672"
            - name: STRIPE_SECRET_KEY
              value: "sk_test_your_stripe_secret_key_here" # En producción, esto se manejaría con K8s Secrets
            - name: STRIPE_WEBHOOK_SECRET
              value: "whsec_your_webhook_secret_here" # También se manejaría con Secrets
            - name: AUTH_SERVICE_URL
              value: "http://auth-service"
            - name: SUBSCRIPTIONS_SERVICE_URL
              value: "http://subscriptions-service"