# k8s/media-deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: nextflop-media-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              value: "your-super-secret-jwt-key-change-in-production"
            - name: MONGODB_URI
              value: "mongodb://admin:password123@mongodb-media:27017/nextflop_media?authSource=admin"
            - name: RABBITMQ_URL
              value: "amqp://admin:password123@rabbitmq:5672"
            - name: AUTH_SERVICE_URL
              value: "http://auth-service"