version: '3.8'

services:
  nextflop:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextflop-app
    ports:
      - "3000:3000"
    env_file:
      - ./src/frontend/.env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    networks:
      - nextflop-network

networks:
  nextflop-network:
    driver: bridge
